### ISSUE TITLE
Google Play | 505 error | INSTALL_FAILED_DUPLICATE_PERMISSION

### ISSUE THREAD

**Issue by nikitamorozov** [yandexmobile/metrica-push-plugin-unity#2]
com.google.android.finsky.installer.ak.onReceive(22): Error -505 while installing com.tnttv.borodach2: INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.tnttv.borodach2 attempting to redeclare permission com.yandex.mobile.metrica.push.sample.unity.permission.C2D_MESSAGE already owned by com.tnttv.borodach

**Comment by bamx23** [comment]
You should replace `com.yandex.mobile.metrica.push.sample.unity` with your package identifier (in AndroidManifest.xml).
