### ISSUE TITLE
com.google.android.gms.gcm.GcmReceiver: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by yapetrichka** [yandexmobile/metrica-push-plugin-unity#6]
При получении пуша возникает ошибка:
java.lang.RuntimeException: Unable to instantiate receiver com.google.android.gms.gcm.GcmReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmReceiver" on path: DexPathList

**Comment by NesterovichAlexey** [comment]
Привет.  Какая версия плагина? И используете ли еще какие-то пуш сервисы?

**Comment by slavaobninsk** [comment]
Качал последнию с gita 0.2.0, сторонних не юзаем, только sdk AppMetrica

**Comment by slavaobninsk** [comment]
GcmReceiver есть в манифесте для отслеживания удалений приложения для sdk AppsFlyer
<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>

**Comment by yapetrichka** [comment]
> Привет. Какая версия плагина? И используете ли еще какие-то пуш сервисы?

Качал последнию с gita 0.2.0, сторонних не юзаем, только sdk AppMetrica

**Comment by yapetrichka** [comment]
GcmReceiver есть в манифесте для отслеживания удалений приложения для sdk AppsFlyer
```
<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>
```

**Comment by NesterovichAlexey** [comment]
GCM считается устаревшим и не рекомендуется гуглом.
Возможно из-за того, что AppMetrica Push Unity Plugin использует firebase возникает конфликт с gcm.
У AppsFlayer есть поддержка Firebase https://support.appsflyer.com/hc/en-us/articles/213766183-Unity-SDK-integration-for-developers#measure-uninstalls
Можешь перейти на Firebase для AppsFlayer?
Или как вариант использовать версию AppMetrica Push Unity Plugin 0.1.0.
Даже если и получиться собрать приложение с firebase и gcm вместе, то могут быть проблемы с отправкой пушей.

**Comment by yapetrichka** [comment]
Ok попробую перевести AppsFlyer на Firebase

**Comment by yapetrichka** [comment]
Перевод на firebase помог
